services:
  - type: web
    name: hotel-booking
    runtime: node
    plan: free
    region: oregon
    buildCommand: pnpm install --frozen-lockfile && pnpm exec prisma generate && pnpm exec next build
    startCommand: pnpm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PRIVATE_STANDALONE
        value: "1"
      - key: PRISMA_SKIP_POSTINSTALL_GENERATE
        value: "true"
      - key: PRISMA_GENERATE_SKIP_AUTOINSTALL
        value: "false"
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXT_PUBLIC_BASE_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: IRCA_API_KEY
        sync: false
      - key: NEXT_PUBLIC_IRCA_API_URL
        value: https://api.irca.org
