#!/bin/bash

# Quick Database Fix Script
# This script helps you set up a new database connection

echo "============================================"
echo "🔧 DATABASE CONNECTION FIX"
echo "============================================"
echo ""
echo "Your current database is unreachable."
echo "The hostname 'ep-young-wave-adg10hd0-pooler.c-2.us-east-1.aws.neon.tech' cannot be resolved."
echo ""
echo "IMMEDIATE ACTIONS REQUIRED:"
echo ""
echo "1️⃣  Go to Neon Console:"
echo "   https://console.neon.tech/"
echo ""
echo "2️⃣  Check your project status:"
echo "   - Is it paused? Click 'Resume'"
echo "   - Was it deleted? Create a new project"
echo ""
echo "3️⃣  Get your connection string:"
echo "   - Click 'Connection Details'"
echo "   - Copy the 'Pooled connection' string"
echo ""
echo "4️⃣  Update your .env file:"
echo "   DATABASE_URL=\"your_new_connection_string\""
echo ""
echo "5️⃣  Push schema to database:"
echo "   npx prisma db push"
echo ""
echo "6️⃣  Generate Prisma Client:"
echo "   npx prisma generate"
echo ""
echo "7️⃣  Restart your dev server:"
echo "   npm run dev"
echo ""
echo "============================================"
echo "For Vercel Deployment:"
echo "============================================"
echo ""
echo "Add these environment variables in Vercel:"
echo ""
echo "DATABASE_URL=your_new_neon_connection_string"
echo "JWT_ACCESS_SECRET=e7d17c8d5fe30a19b402941ed283cf69c20bf17e37e39c905bdf0c352db34066"
echo "JWT_REFRESH_SECRET=b6d7505c29d197a7c3abe8fa8bb63fa3ddbd7679c911f54834343ebfc0e2c6cd"
echo "NEXTAUTH_SECRET=your-secret-key-here-change-in-production"
echo "NEXTAUTH_URL=https://your-vercel-app.vercel.app"
echo ""
echo "============================================"
